#!/bin/bash

if [ -z "${BUILDKITE_PLUGIN_S3_CACHE_BUCKET}" ]; then
  echo '+++ 🚨 Missing MinIO bucket configuration'
  exit 1
fi

if [ -z "${BUILDKITE_PLUGIN_MINIO_CACHE_ALIAS}" ]; then
  echo '+++ 🚨 Missing MinIO alias configuration'
  exit 1
fi

build_key() {
  if [ -n "${BUILDKITE_PLUGIN_S3_CACHE_PREFIX}" ]; then
    echo "${BUILDKITE_PLUGIN_S3_CACHE_PREFIX}/${1}"
  else
    echo "$1"
  fi
}

verbose() {
  if [ -n "${BUILDKITE_PLUGIN_S3_CACHE_ONLY_SHOW_ERRORS}" ]; then
    echo "--quiet"
  else
    echo ""
  fi
}

restore_cache() {
  local from="$1"
  local to="$2"
  # We want word splitting to interpolate options
  # shellcheck disable=SC2046
  mc mirror --preserve $(verbose) "${BUILDKITE_PLUGIN_MINIO_CACHE_ALIAS}/${BUILDKITE_PLUGIN_S3_CACHE_BUCKET}/$(build_key "${from}")" "${to}"
}

save_cache() {
  local to="$1"
  local from="$2"
  # We want word splitting to interpolate options
  # shellcheck disable=SC2046
  mc mirror --preserve $(verbose) "${from}" "${BUILDKITE_PLUGIN_MINIO_CACHE_ALIAS}/${BUILDKITE_PLUGIN_S3_CACHE_BUCKET}/$(build_key "${to}")"
}

exists_cache() {
  if [ -z "$1" ]; then exit 1; fi
  [ -n "$(mc find "${BUILDKITE_PLUGIN_MINIO_CACHE_ALIAS}/${BUILDKITE_PLUGIN_S3_CACHE_BUCKET}/$(build_key "$1")")" ]
}

OPCODE="$1"
shift

if [ "$OPCODE" = 'exists' ]; then
  exists_cache "$@"
elif [ "$OPCODE" = 'get' ]; then
  restore_cache "$@"
elif [ "$OPCODE" = 'save' ]; then
  save_cache "$@"
else
  exit 255
fi
